### PR TITLE
Various Editing Shenanigans

### PR DESCRIPTION
**Pull request by ericnograles**
@johnrhampton Looks great so far, but I found the blockquotes a little difficult to read.  Wanna check this out and see if the formatting is ok with you?  Thanks!

### CODE REVIEW

**Comment by ericnograles** [comment]
We also might want to have the bash commands optional.  This is to accommodate folks with Windows machines, of which there will be plenty.

**Comment by ericnograles** [comment]
...aaand went ahead and bullet-pointed the bash commands  lol

Let me know if this looks good to you.

**Comment by joshburgess** [comment]
You can use those commands on Windows with a shell called Cmder. Free and easy .zip download holding an .exe... no installation needed. Also comes prepackaged with Git.

**Comment by ericnograles** [comment]
Yep thought of that too, or even something old school like Cygwin.  But, let's try to keep it as agnostic as possible.  Windows devs can be...fickle.  We want to ease them into this slowly.  ;-)

**Comment by johnrhampton** [comment]
Nice @ericnograles.. Good call on making the bash optional.  People can def just roll those commands in their IDE.

**Pull request merged**
